### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by fataltes** [Kingsford-Group/splitsbt#1]
Hi Brad ,

We went through the manual and tried to build SplitSBT but we get the following error:
```
Count.cc:91:25: error: no matching function for call to 'jellyfish::stream_manager<__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > > >::stream_manager()'
Count.cc:94:17: error: 'stream_manager_type {aka class jellyfish::stream_manager<__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > > >}' has no member named 'paths'
Count.cc:97:15: error
```
It looks like that SSBT is looking for a member of the class *stream_manager* in jellyfish that doesn't exist. 
The error is reproducible with jellyfish versions 2.2.6, 2.2.0.

Do you have any ideas why it's happening or any suggestions how to solve it?

**Comment by Bradsol** [comment]
I'm pretty sure this is an error arising from some of my latest changes to permit count to handle bam files as input. I've 'released' an earlier commit which should not have this problem. Let me know if it does!

As an aside, you can also use the SBT count command to produce the same filters used in SSBT. The only difference in output at the moment is the '.sim.bf.bv' (SSBT) versus '.bf.bv' (SBT) which would have to be manually adjusted.

**Comment by fataltes** [comment]
Thanks Brad,

That worked.

**Comment by RSherman15** [comment]
I was having this issue as well, and while using the release version did fix the issue, it would be great to be able to use bams as input to count (or even gzipped fastqs directly) rather than fasta. Any chance that a fix to the issue/support for bams will be released shortly?

**Comment by Bradsol** [comment]
You can pass in gzipped fasta/fastq by writing to stdout and passing that in as an argument.

For example: 
```
./bt count myhashfile.hh 2e9 <(gunzip -c SRRXXX.fasta.gz) SRRXXX.bf.bv
```

The bam reader is also functional in the latest commit but requires HTSLIB to work.

**Comment by RSherman15** [comment]
Great, thanks!
