### ISSUE TITLE
Compress not implemented

### ISSUE THREAD

**Issue by Colelyman** [Kingsford-Group/splitsbt#10]
When I run `./src/bt compress` (with the parameters from the manual) for one sequence, I get the following output:

    Starting Bloom Tree
    Kmer size = 20
    Compressing..
    Read 1 nodes in Bloom Tree
    Load_size: 10000000
    fatal: Not implemented 

Any idea when this will be implemented or what this message indicates?

Thanks!

**Comment by Bradsol** [comment]
What type of bloom filter node are you compressing? (What is the extension of the bloom filter file?)

**Comment by Colelyman** [comment]
I am trying to compress a `bf.bv` node. Is this what you are referring to @Bradsol?

**Comment by Colelyman** [comment]
If it helps, my entire script is as follows

```bash
WORKING_DIR=$1
SSBT=/home/colelyman/code/splitsbt/src/bt
GENOME=<path to human genome>
BASE_GENOME=$WORKING_DIR/`basename $GENOME .fasta`
K=20
NB_HASHES=1
BF_SIZE=10000000
CUTOFF=3
NUM_THREADS=4

mkdir -p $WORKING_DIR

# initalize the hash functions
/usr/bin/time -v $SSBT hashes -k $K $WORKING_DIR/ssbt.hashes $NB_HASHES &> $WORKING_DIR/hashes.out

# convert the file to a bloom filter vector
/usr/bin/time -v $SSBT count --cutoff $CUTOFF --threads $NUM_THREADS $WORKING_DIR/ssbt.hashes $BF_SIZE $GENOME $BASE_GENOME.bf.bv &> $WORKING_DIR/count.out

echo $BASE_GENOME.bf.bv &> $WORKING_DIR/list.txt

# compile a list of the bit vectors
/usr/bin/time -v $SSBT build --sim-type 0 $WORKING_DIR/ssbt.hashes $WORKING_DIR/list.txt $WORKING_DIR/ssbt.bloomtree &> $WORKING_DIR/build.out

# compress bit vectors
/usr/bin/time -v $SSBT compress $WORKING_DIR/ssbt.bloomtree $WORKING_DIR/ssbt.bloomtree.compressed &> $WORKING_DIR/compress.out
```

**Comment by Bradsol** [comment]
Ah I see the issue. ".bf.bv" is the extension for an Uncompressed SBT filter. ".sim.bf.bv" is the extension for an Uncompressed SSBT filter. 

If you are trying to compress the filter as an SBT filter, you currently have to use SBT to do that.
If you are trying to compress the filter as an SSBT filter, you need to rename your bloom filters as SSBT filters [ just change the extension from .bv to .sim.bf.bv]

**Comment by Colelyman** [comment]
That worked, thanks so much!
