### ISSUE TITLE
Error when running bt build

### ISSUE THREAD

**Issue by MinghaoYan** [Kingsford-Group/splitsbt#12]
Hi,

I followed the pipeline in doing the bt hashes and bt count as suggested in the manual. But I had this error when building the tree structure.

The command I used was 
`./bt build hashfile listoffiles.txt bloomtreefile`
where hashfile is the file written to in hashes command and listoffiles.txt is the result of 
`ls *.bf.bv > listoffiles.txt `
as suggested in the user manual.

Any idea where the problem might come from? Thank you very much in advance!

Below is a sample log from the build command:

> Starting Bloom Tree
Kmer size = 20
Building...
With build type 1
Building tree on 2 bloom filters.
Loading hashes from hashfile
Hash applications=4
Read hashes for k=20
Inserting leaves into tree...
Inserting leaf ERR1001628.bf.bv ... 
Inserting leaf ERR1014538.bf.bv ... 
At node: ERR1001628.bf.bv
Load_size: 50000000
Load_size: 50000000
fatal: Split Bloom Filter bf() should be SBF.

The log from count command looks like this:
> Starting Bloom Tree
Kmer size = 20
Done.
Starting Bloom Tree
Kmer size = 20
Loading hashes from hashfile
Hash applications=4
Read hashes for k=20
Cutoff Count: 3
HAVE_HTSLIB FLAG: TRUE
Processing fast[aq] file.
thread 9 added 47988146
thread 11 added 47397334
thread 14 added 48744594
thread 6 added 47465136
thread 3 added 43617110
thread 4 added 46407926
thread 13 added 44366352
thread 0 added 41060747
thread 5 added 45091007
thread 12 added 44834009
thread 7 added 47982400
thread 8 added 49298228
thread 15 added 42275499
thread 10 added 43339601
thread 2 added 45574623
thread 1 added 48018955
Right before cutoff count: 3
in hash: 98841121 in blom: 5848576
Done.
Starting Bloom Tree
Kmer size = 20
Loading hashes from hashfile
Hash applications=4
Read hashes for k=20
Cutoff Count: 3
HAVE_HTSLIB FLAG: TRUE
Processing fast[aq] file.
thread 10 added 131168500
thread 13 added 142982200
thread 11 added 134459361
thread 9 added 126773940
thread 5 added 140243650
thread 8 added 141631535
thread 14 added 131927493
thread 0 added 144947939
thread 15 added 136607013
thread 7 added 141231837
thread 4 added 135919838
thread 6 added 134475999
thread 1 added 134499074
thread 12 added 132088707
thread 2 added 137241043
thread 3 added 139496367
Right before cutoff count: 3
in hash: 215465214 in blom: 12194764
Done.

**Comment by Bradsol** [comment]
This is a relatively simple fix: You are trying to build a Split SBT using regular SBT filters. As the code bases are integrated, the build method uses the suffix of the filters to judge how to construct them. If you adjust your suffixes from '.bf.bv' [the SBT default] to '.sim.bf.bv' [the SSBT default for leaves] it should run normally.

EDIT: It's worth noting that the only change that is necessary is the suffix. The actual filters themselves are the same -- though the SSBT will adjust the filters during the construction step as it moves bits from the leaves to further up the tree based on similarity.

**Comment by MinghaoYan** [comment]
That fixed my problem! Thank you very much for the immediate response!
