### ISSUE TITLE
potential deallocation problem

### ISSUE THREAD

**Issue by rsharris** [Kingsford-Group/splitsbt#4]
I'm pretty sure that "delete buf" at line 54 in Build.cc should be "delete[] buf".  Buf was allocated as an array but is being deleted as an object.

The second answer at
https://stackoverflow.com/questions/4255598/delete-vs-delete/4255636
quotes the standard, which indicates that deleting an allocated array with the delete object operator is undefined.

Some compilers (e.g. clang) warn on this statement.  Others are silent, and perhaps both produce correct code for it(?).

**Comment by Bradsol** [comment]
That is a good find. I'll correct that in the next commit.

**Comment by rsharris** [comment]
Credit goes to clang for warning me about it.

**Comment by Bradsol** [comment]
Corrected this but forgot to close the issue. Thanks again!
