### ISSUE TITLE
list-like tree structure

### ISSUE THREAD

**Issue by fataltes** [Kingsford-Group/splitsbt#7]
Hi,

I tried to run ssbt (in the master branch) on a set of 200 bitvectors, each of size ~19Mb as leaves and the tree structure that I got back was sort of like a list rather than a tree with each leaf adding a new level to the tree. 
Is this output expected and if yes, what characteristic of the input bitvectors do you think might cause such a behavior?

I'm attaching the output tree structure file in case it is helpful.

[test200.txt](https://github.com/Kingsford-Group/splitsbt/files/2128762/test200.txt)

Thank you,
Fatemeh

**Comment by Bradsol** [comment]
I was thinking some more about this since we talked - what similarity metric are you using? Set the sim-type to 1 if it isnt

**Comment by fataltes** [comment]
The default, which is 0, right?

I'll rerun it with sim=1

Thanks

**Comment by Bradsol** [comment]
We talked about this in person - closing the issue.
